<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sendion.Hosting\Sendion.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Sendion.Persistence.MongoDb\Sendion.Persistence.MongoDb.csproj" />
    <ProjectReference Include="..\..\src\Sendion.Transport.Kafka\Sendion.Transport.Kafka.csproj" />
  </ItemGroup>

</Project>
